trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # This specifies a Microsoft-hosted agent with the latest Ubuntu image

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
