name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/my-flask-app:${{ github.sha }} .
          docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-flask-app:${{ github.sha }}

      - name: Deploy to Azure Container Instance
        run: |
          EXISTS=$(az container show --resource-group resourcegroup111 --name mycontainerinstance --query "id" -o tsv)
          if [ -z "$EXISTS" ]; then
            az container create --resource-group resourcegroup111 --name mycontainerinstance --image ${{ secrets.ACR_LOGIN_SERVER }}/my-flask-app:${{ github.sha }} --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} --registry-username ${{ secrets.ACR_USERNAME }} --registry-password ${{ secrets.ACR_PASSWORD }} --dns-name-label myflaskappdnslabel --ports 80
          else
            az container restart --resource-group resourcegroup111 --name mycontainerinstance
          fi
